### PR TITLE
Add support for latest kernel driver and dynamic MAC address

### PR DESCRIPTION
**Pull request by ivanbratovic**
This PR adds support for latest Dualsense Driver in the current kernel version. I've tested this on my machine using the 5.16.0 kernel. The controller is exposed in a different directory, within `/sys/devices`. For example, one of my controllers is at `/sys/devices/pci0000:00/0000:00:08.1/0000:05:00.3/usb1/1-3/1-3:1.3/0003:054C:0CE6.000A/`.

I've added automatic controller path discovery, using the `find` GNU command within the `subprocess` Python module. This method also removes the need for the user to enter the MAC address of their device. However, it must be noted that **the user cannot configure more than one controller at a time**.

Finally, I've removed some magic strings regarding the paths and extracted them to variables.

### CODE REVIEW

**Comment by cow-killer** [comment]
Nice work, however I'm unable to use the program on my side (running it just says it couldn't pick the controller up), either through USB or Bluetooth on kernel 5.16.1. The path to my controller is in `/sys/devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11:1.3/0003:054C:0CE6.000D` I think your controller is in one folder extra. Maybe that's why the script can't parse the path on my end.

EDIT: in the process of debugging this, see if I can see what's going on.

**Comment by cow-killer** [comment]
Ah, found out what it was: the `battery_path` variable in line 23 had `power_supply` in the file path twice. After getting rid of that the program opens up. Give me a few minutes to test this and I will probably merge this.

**Comment by cow-killer** [comment]
So after digging a little further, to get the LEDs to work, I need to move up one directory. My LED path is `/sys/devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11:1.3/0003:054C:0CE6.000D/leds/input40:white:player`, but in the program it's set as `/sys/devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11:1.3/0003:054C:0CE6.000D/power_supply/leds/input40:white:player`. I'm having a hard time trying to figure out how to move to the parent directory here, is there a simple way to move up?

EDIT: nevermind, I found a fix. I had to import `Path` from `pathlib`, then add these lines:
```
parent_path = Path(device_path) # need to get parent directory so we can modify LEDs
parent_path = parent_path.parent
```
Then set `player_leds_path` and `rgb_leds_path` to `parent_path`. Program works as it should now. Can you run this and see if it works on your side?
[ds_led.zip](https://github.com/cow-killer/dualsense-led-configurator/files/7927985/ds_led.zip)

**Comment by ivanbratovic** [comment]
Hi! Thanks for checking the PR so soon. I haven't found time to check your changes until now.

I did not expect the number of subdirectories to be variable. It's a great idea using the parent path, rather than the explicit number of subdirectories I used. I've implemented this idea in code, but without using the `pathlib` module, but only Python's indexing operator. Please check that this finally works on your device.

I've also added your comments in my section of code.

**Comment by cow-killer** [comment]
Works fine on my side. I had some folks on [r/linux_gaming](https://www.reddit.com/r/linux_gaming/comments/scgp5o/dualsense_owners_testers_wanted_for_a_led_program/) give this PR a shot. One user had to change `input_num` to this:
```
input_path = subprocess.check_output(["find", "/sys/devices/", "-name", "input*:white:player-1"])
input_path = input_path.decode().split("/")[-1]
input_path_index = 5
input_num = ""
while input_path[input_path_index] != ":" :
    input_num = input_num + input_path[input_path_index]
    input_path_index += 1
```
Because it's only one digit on his side (rather than two.) If you change `input_num` to that last bit of code, run the script again, and verify that it works, I think we'll be safe to merge this.

**Comment by ghost** [comment]
Hi, saw this on reddit.

PR works fine for me too. 

Regarding the one digit issue, instead of a while loop it can be done like this

```
input_path = subprocess.check_output(["find", "/sys/devices/", "-name", "input*:white:player-1"])
input_path = input_path.decode().split("/")[-1]
input_num = input_path.split(":")[0][5:]
```

**Comment by ivanbratovic** [comment]
I've implemented the solution, which is the same as in the @RTFMExe's comment. I feel it is more "Pythonier" then a `while` loop. If you think the code readability suffered due to this, I can break the code up into more chunks. The solution should also work for any n-digit input number.

Hopefully, that's all the major issues fixed, but I'll keep my eye on any new Issues regarding this.

**Comment by cow-killer** [comment]
Changes look good! The new code for `input_path` is much cleaner. Thanks both of you for your help!

**Pull request merged**
